### ISSUE TITLE
Admin button not showing up if another mixin is loaded first

### ISSUE THREAD

**Issue by hermanocabral** [modlinltd/django-advanced-filters#26]
Howdy,

I'm facing an issue where the "advanced filter" button doesn't show up in the admin page (Django 1.9) if I have another mixin loaded first.

The mixin being loaded first is from django-import-export: https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L401

eg. 
```
class WhateverAdmin(ImportExportMixin, AdminAdvancedFiltersMixin, admin.ModelAdmin):
    pass
```

Anyone ever experienced that?

Thanks.

**Comment by asfaltboy** [comment]
Yes, that is expected, since AFAIK Django only allows one custom template to be declared per `ModelAdmin`. What I suggest you to do is merge both [django-advanced-filter's custom `change_list` template][1] and [django-import-export's custom `change_list` template][2] into [your own custom template][3] and declare it in your `ModelAdmin` class; or, if you intend to do this in multiple classes, a mixin like this can work:

```python
class CommonAdminMixin(ImportExportMixin, AdminAdvancedFiltersMixin):
    """
    Set a custom ``change_list_template`  to enable both `django-import-export`_ and
    `django-advanced-filters`_ functionality in the ``change_list`` admin view.
    """
    #: template for change_list view
    change_list_template = 'admin/change_list_common.html'
```

Unfortunately I don't know of any clean way to merge templates, you probably can just copy paste the content of import-export into advanced-filters and save in your template folder.

[1]: https://github.com/modlinltd/django-advanced-filters/blob/develop/advanced_filters/templates/admin/advanced_filters.html
[2]: https://github.com/django-import-export/django-import-export/blob/master/import_export/templates/admin/import_export/change_list_import.html
[3]: https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#custom-template-options

**Comment by hermanocabral** [comment]
👍  bro, that's what I had done in the meantime, guess there's no way around it...

Thanks for the help!
